[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/archive"
  to = "/archive.html"
  status = 200

[[redirects]]
  from = "/apply"
  to = "/apply.html"
  status = 200

[[redirects]]
  from = "/preview"
  to = "/preview.html"
  status = 200
